
import {state,user,available,activeLoans,unpaid} from "./state.js";
import {esc,formatDate,money,initials,today} from "./utils.js";
import {pageHeader,card,empty,themeTrigger,themePopup} from "./ui.js";

export function dashboard(){
  const total=state.db.books.reduce((a,b)=>a+Number(b.copies||0),0),av=state.db.books.reduce((a,b)=>a+available(b),0),loans=state.db.loans.filter(x=>!x.returned),overdue=loans.filter(x=>x.dueDate<today()),fine=unpaid().reduce((a,x)=>a+Number(x.amount||0),0);
  return pageHeader("Dashboard","A clear view of your library.",`<button class="btn" data-open-issue>Issue book</button>`)+
  `<div class="stats"><div class="card stat"><span>Titles</span><strong>${state.db.books.length}</strong><small>${total} total copies</small></div><div class="card stat"><span>Members</span><strong>${state.db.users.filter(x=>x.role==="member").length}</strong><small>Member accounts</small></div><div class="card stat"><span>Issued</span><strong>${loans.length}</strong><small>${overdue.length} overdue</small></div><div class="card stat"><span>Unpaid fines</span><strong>${money(fine,state.db.settings.currency)}</strong><small>${unpaid().length} records</small></div></div>
  <div class="grid2"><div class="card pad"><div class="section-head"><h2>Collection</h2><span class="badge">${av}/${total} available</span></div><div class="progress"><i style="width:${total?Math.round(av/total*100):0}%"></i></div><p class="muted">${total?Math.round(av/total*100):0}% of copies are available.</p></div>
  <div class="card pad"><div class="section-head"><h2>Quick actions</h2></div><div class="quick-grid"><button class="quick" data-nav="books"><b>＋</b>Add or manage books</button><button class="quick" data-nav="members"><b>♙</b>Manage members</button><button class="quick" data-nav="circulation"><b>↔</b>Circulation</button><button class="quick" data-nav="reports"><b>▥</b>Reports</button></div></div></div>
  <div class="card pad mt"><div class="section-head"><h2>Recent activity</h2><button class="link" data-nav="audit">View all</button></div>${state.db.audit.slice(0,7).map(a=>`<div class="activity"><span class="avatar">${esc(initials(a.user))}</span><div class="activity-main"><b>${esc(a.action)}</b><small>${esc(a.detail||"")}</small></div><time>${formatDate(a.time,state.db.settings.dateFormat)}</time></div>`).join("")||empty("No activity yet.")}</div>`;
}
export function books(){
  return pageHeader("Books","Build a clean catalogue with only the essentials required.",`<button class="btn" data-add-book>＋ Add book</button>`) + `<div class="filterbar"><input id="bookSearch" value="${esc(state.bookSearch)}" placeholder="Search title, author, ISBN or genre" autocomplete="off"><span class="muted" id="bookCount"></span></div>${card(`<div class="table-wrap"><table><thead><tr><th>Book</th><th>ISBN</th><th>Genre</th><th>Copies</th><th>Available</th><th>Year</th><th>Actions</th></tr></thead><tbody id="bookRows"></tbody></table></div>`,"table-card")}`;
}
export function members(){
  return pageHeader("Students & Members","Register students and manage member accounts.",`<button class="btn" data-add-member>＋ Register student</button>`) + `<div class="filterbar"><input id="memberSearch" value="${esc(state.memberSearch)}" placeholder="Search members" autocomplete="off"><span class="muted" id="memberCount"></span></div>${card(`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Roll number</th><th>Contact</th><th>Type</th><th>Loans</th><th>Fines</th><th>Status</th><th>Actions</th></tr></thead><tbody id="memberRows"></tbody></table></div>`,"table-card")}`;
}
export function circulation(){return pageHeader("Circulation","Issue, renew and return books.",`<button class="btn" data-open-issue>＋ Issue book</button>`)+card(`<div class="table-wrap"><table><thead><tr><th>Book</th><th>Member</th><th>Issued</th><th>Due</th><th>Status</th><th>Actions</th></tr></thead><tbody id="loanRows"></tbody></table></div>`,"table-card")}
export function reservations(){return pageHeader("Reservations","Manage the waiting queue.")+card(`<div class="table-wrap"><table><thead><tr><th>Book</th><th>Member</th><th>Placed</th><th>Status</th><th>Action</th></tr></thead><tbody id="reservationRows"></tbody></table></div>`,"table-card")}
export function fines(){return pageHeader("Fines","Track outstanding and paid fines.")+card(`<div class="table-wrap"><table><thead><tr><th>Member</th><th>Book</th><th>Amount</th><th>Created</th><th>Status</th><th>Action</th></tr></thead><tbody id="fineRows"></tbody></table></div>`,"table-card")}
export function notifications(){state.db.notifications.forEach(n=>n.read=true);state.db.updatedAt=Date.now();return pageHeader("Notifications","Library reminders and messages.")+card(`<div id="notificationList"></div>`,"pad")}
export function audit(){return pageHeader("Activity","Recent administrator actions.")+card(`<div class="table-wrap"><table><thead><tr><th>Date</th><th>User</th><th>Action</th><th>Details</th></tr></thead><tbody id="auditRows"></tbody></table></div>`,"table-card")}
export function reports(){return pageHeader("Reports","Export library records as CSV or the full database as JSON.")+`<div class="reports-grid"><div class="card report-card"><h2>Books</h2><p>Catalogue, copies, availability and metadata.</p><button class="btn secondary" data-export="books">Download books CSV</button></div><div class="card report-card"><h2>Members</h2><p>Member accounts and status.</p><button class="btn secondary" data-export="members">Download members CSV</button></div><div class="card report-card"><h2>Loans</h2><p>Issue, due and return history.</p><button class="btn secondary" data-export="loans">Download loans CSV</button></div><div class="card report-card"><h2>Fines</h2><p>Fine amounts and payment status.</p><button class="btn secondary" data-export="fines">Download fines CSV</button></div></div>`}
export function settings(){const s=state.db.settings;return pageHeader("Settings","Library rules, appearance and database tools.")+`<div class="settings-grid"><div class="card pad"><form id="settingsForm"><div class="section-head"><h2>Library rules</h2><span class="badge">Saved on button click</span></div><div id="settingsFields"></div><div class="form-error" id="settingsError"></div><div class="form-actions"><button type="button" class="btn secondary" data-reset-settings>Reset</button><button type="submit" class="btn">Save settings</button></div></form></div><div class="card pad"><h2>Appearance</h2><p class="muted">Theme is stored separately from the library database.</p><div class="theme-grid" id="themeGrid"></div><h2 class="mt-xl">Database</h2><p class="muted">LocalStorage is the live database. JSON backup is portable between localhost and GitHub Pages.</p><div id="storageStatus"></div><div class="stack"><button class="btn" data-backup>Download full JSON backup</button><label class="btn secondary">Restore JSON backup<input id="restoreInput" type="file" accept=".json,application/json" hidden></label><button class="btn danger" data-clear>Clear database</button></div><div class="notice mt"><b>Remember:</b> localhost and GitHub Pages have separate LocalStorage origins. Use the JSON backup to move data between them.</div></div></div>`}
export function setup(){return `<main class="auth-page"><section class="card auth-card"><div class="brand-large"><span class="brand-mark">L</span><div><strong>Library Management</strong><small>School & College Edition</small></div></div><p class="muted">Create the first administrator account.</p><form id="setupForm"><div class="form-grid two"><label class="field"><span>Full name</span><input name="name" required autocomplete="name"></label><label class="field"><span>Username</span><input name="username" required autocomplete="username"></label><label class="field"><span>Email</span><input name="email" type="email" required autocomplete="email"></label><label class="field"><span>Password</span><input name="password" type="password" minlength="8" required autocomplete="new-password"></label><label class="field"><span>Library name</span><input name="libraryName" value="Library Management" required></label></div><p class="hint">Leave email-domain restrictions empty to allow any valid email address.</p><div class="form-error" id="setupError"></div><div class="form-actions"><button class="btn" type="submit">Create administrator</button></div></form></section></main>`}
export function login(){return `<main class="auth-page"><section class="card auth-card"><div class="brand-large"><span class="brand-mark">L</span><div><strong>Library Management</strong><small>Sign in</small></div></div><form id="loginForm"><div class="form-grid"><label class="field"><span>Username</span><input name="username" required autocomplete="username"></label><label class="field"><span>Password</span><input name="password" type="password" required autocomplete="current-password"></label></div><div class="form-error" id="loginError"></div><div class="form-actions"><button class="btn" type="submit">Sign in</button></div></form></section></main>`}
export function memberHome(){
  const u=user(),loans=activeLoans(u.id),f=unpaid(u.id),r=state.db.reservations.filter(x=>x.memberId===u.id&&x.status==="active");
  const overdue=loans.filter(x=>x.dueDate<today()).length;
  const fineTotal=f.reduce((sum,x)=>sum+Number(x.amount||0),0);
  const bookName=id=>state.db.books.find(b=>b.id===id)?.title||"Book";
  const borrowedIds=new Set(loans.map(x=>x.bookId));
  const totalCopies=state.db.books.reduce((n,b)=>n+Number(b.copies||0),0);
  const availableCopies=state.db.books.reduce((n,b)=>n+available(b),0);
  const availableTitles=state.db.books.filter(b=>available(b)>0).length;
  return `<div class="member-app">
    <header class="member-topbar">
      ${themeTrigger()}
      <div class="member-brand"><span class="brand-mark">L</span><div><strong>${esc(state.db.settings.libraryName)}</strong><small>Student Member Portal</small></div></div>
      <div class="member-top-actions"><span class="member-user-chip"><span class="avatar">${esc(initials(u.name))}</span><span>${esc(u.name)}</span></span><button class="btn secondary member-signout" type="button" data-logout>↪ Sign out</button></div>
      ${themePopup()}
    </header>
    <main class="member-page">
      <section class="member-hero">
        <div class="member-hero-main">
          <span class="member-eyebrow">${esc(state.db.settings.libraryName)} · Member account</span>
          <h1>Welcome back, ${esc(u.name.split(/\s+/)[0])}</h1>
          <p>Check your borrowed books, see which catalogue titles are available, review reservations and keep track of fines — all from one place.</p>
        </div>
        <div class="member-hero-mini"><span>${availableTitles}</span><small>titles currently available</small></div>
      </section>
      <section class="member-summary">
        <div class="member-stat"><span class="member-stat-icon">▤</span><div><small>My borrowed books</small><strong>${loans.length}</strong><em>${overdue?`${overdue} overdue`:"No overdue books"}</em></div></div>
        <div class="member-stat"><span class="member-stat-icon">◷</span><div><small>Reservations</small><strong>${r.length}</strong><em>${r.length?"Active reservations":"Nothing reserved"}</em></div></div>
        <div class="member-stat"><span class="member-stat-icon">₹</span><div><small>Outstanding fines</small><strong>${money(fineTotal,state.db.settings.currency)}</strong><em>${f.length?`${f.length} record${f.length===1?"":"s"}: payment due`:"Account is clear"}</em></div></div>
      </section>
      <div class="member-grid member-grid-enhanced">
        ${card(`<div class="member-card-head"><div><span class="section-kicker">Profile</span><h2>My details</h2></div><span class="avatar-lg">${esc(initials(u.name))}</span></div><div class="member-profile-name"><strong>${esc(u.name)}</strong><span>${esc(u.memberType||"Member")}</span></div><div class="statline"><span>Roll number</span><b>${esc(u.rollNumber||"—")}</b></div><div class="statline"><span>Email</span><b>${esc(u.email)}</b></div><div class="statline"><span>Phone</span><b>${esc(u.phone||"—")}</b></div>`,`member-card profile-card`)}
        ${card(`<div class="member-card-head"><div><span class="section-kicker">Borrowed books</span><h2>My current loans</h2></div><span class="badge ${overdue?"bad":"good"}">${overdue?`${overdue} overdue`:"Up to date"}</span></div>${loans.length?`<div class="member-list">${loans.map(l=>`<div class="member-list-item"><div><b>${esc(bookName(l.bookId))}</b><small>Due ${formatDate(l.dueDate,state.db.settings.dateFormat)}</small></div><span class="badge ${l.dueDate<today()?"bad":"good"}">${l.dueDate<today()?"Overdue":"Borrowed"}</span></div>`).join("")}</div>`:empty("You do not have any books issued right now.")}`,'member-card')}
        ${card(`<div class="member-card-head"><div><span class="section-kicker">Catalogue</span><h2>Books & borrowing status</h2><p class="member-card-subtitle">See every book in the library and whether you currently have it.</p></div><span class="badge good">${availableCopies}/${totalCopies} copies free</span></div>${state.db.books.length?`<div class="member-book-list">${state.db.books.map(b=>{const borrowed=borrowedIds.has(b.id),free=available(b);return `<div class="member-book-row"><div class="member-book-main"><span class="member-book-icon">▤</span><div><b>${esc(b.title)}</b><small>${esc(b.author)}${b.genre?` · ${esc(b.genre)}`:""}</small></div></div><div class="member-book-meta"><span class="badge ${borrowed?"warn":free>0?"good":"bad"}">${borrowed?"Borrowed":"Not borrowed"}</span><small>${free>0?`${free} ${free===1?"copy":"copies"} available`:"No copies available"}</small></div></div>`}).join("")}</div>`:empty("No books have been added to the catalogue yet.")}`,'member-card member-catalogue')}
        ${card(`<div class="member-card-head"><div><span class="section-kicker">Money</span><h2>Outstanding fines</h2></div><span class="badge ${f.length?"bad":"good"}">${f.length?"Payment due":"Clear"}</span></div>${f.length?`<div class="member-list">${f.map(x=>`<div class="member-list-item"><div><b>${esc(bookName(x.bookId))}</b><small>Outstanding library fine</small></div><strong>${money(x.amount,state.db.settings.currency)}</strong></div>`).join("")}</div>`:empty("You have no outstanding fines.")}`,'member-card')}
        ${card(`<div class="member-card-head"><div><span class="section-kicker">Waiting list</span><h2>Reservations</h2></div><span class="badge">${r.length} active</span></div>${r.length?`<div class="member-list">${r.map(x=>`<div class="member-list-item"><div><b>${esc(bookName(x.bookId))}</b><small>Reservation placed ${formatDate(x.createdAt,state.db.settings.dateFormat)}</small></div><span class="badge">${esc(x.status)}</span></div>`).join("")}</div>`:empty("You have no active reservations.")}`,'member-card')}
      </div>
      <p class="member-security-note">Your theme preference is saved to this browser. Signing out ends this browser session; your library data remains stored in LocalStorage.</p>
    </main>
  </div>`;
}
