
import * as Pages from "./pages.js";
import {state,user} from "./state.js";
import {layout,applyTheme} from "./ui.js";
import {storageAvailable,clearDB,exportDB,importDB} from "./storage.js";
import {field,select,themes,setTheme,toast,themeLabel} from "./ui.js";
import {esc,formatDate,money,initials,today,csv,download,validEmail,domain,addDays} from "./utils.js";
import {DEFAULT_SETTINGS} from "./config.js";
import {persist,logout,login,audit,available,activeLoans,unpaid,notify} from "./state.js";
import {bookForm,memberForm,issueForm,reservationForm} from "./forms.js";

export function render(){applyTheme();const u=user();if(!state.db.users.length){document.querySelector("#app").innerHTML=Pages.setup();bindSetup();return}if(!u){document.querySelector("#app").innerHTML=Pages.login();bindLogin();return}if(u.role==="member"){document.querySelector("#app").innerHTML=Pages.memberHome();bindMemberPage();return}const fn=Pages[state.page]||Pages.dashboard;layout(fn());bindPage();refreshPageData()}
function bindMemberPage(){
  document.querySelector("[data-logout]")?.addEventListener("click",()=>{logout();render();toast("Signed out successfully.")});
  bindThemeMenu();
}
function bindThemeMenu(){
  const trigger=document.querySelector("[data-theme-menu]"),pop=document.querySelector("[data-theme-popover]");
  if(!trigger||!pop)return;
  const outside=e=>{if(!pop.contains(e.target)&&!trigger.contains(e.target))close()};
  const close=()=>{pop.classList.remove("open");trigger.setAttribute("aria-expanded","false");document.removeEventListener("click",outside)};
  trigger.addEventListener("click",e=>{e.stopPropagation();const open=pop.classList.toggle("open");trigger.setAttribute("aria-expanded",String(open));if(open)document.addEventListener("click",outside)});
  pop.querySelector("[data-close-theme]")?.addEventListener("click",close);
  pop.querySelectorAll("[data-theme]").forEach(x=>x.addEventListener("click",()=>{setTheme(x.dataset.theme);close();toast(`${themeLabel(x.dataset.theme)} theme applied.`)}));
}

function bindSetup(){document.querySelector("#setupForm").addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),err=document.querySelector("#setupError");err.textContent="";const name=String(fd.get("name")).trim(),username=String(fd.get("username")).trim(),email=String(fd.get("email")).trim(),password=String(fd.get("password")),libraryName=String(fd.get("libraryName")).trim()||"Library Management";if(!/^[\p{L}][\p{L} .'-]{1,79}$/u.test(name))return err.textContent="Enter a valid name.";if(!/^[A-Za-z0-9_.-]{3,30}$/.test(username))return err.textContent="Username must be 3–30 characters.";if(!validEmail(email))return err.textContent="Enter a valid email.";if(password.length<8)return err.textContent="Password must contain at least 8 characters.";state.db.settings.libraryName=libraryName;const u={id:crypto.randomUUID?.()||Date.now()+"",name,username,email,password,role:"admin",active:true,createdAt:Date.now()};state.db.users.push(u);audit("Create administrator",username);persist();login(u);render();toast("Administrator created.")})}
function bindLogin(){document.querySelector("#loginForm").addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),err=document.querySelector("#loginError"),u=state.db.users.find(x=>x.username.toLowerCase()===String(fd.get("username")).trim().toLowerCase());if(!u)return err.textContent="No such user.";if(u.password!==String(fd.get("password")))return err.textContent="Wrong password.";if(u.active===false)return err.textContent="This account is disabled.";login(u);audit("Login");persist();render();toast("Signed in.")})}
function bindPage(){
  document.querySelectorAll("[data-nav]").forEach(x=>x.addEventListener("click",()=>{state.page=x.dataset.nav;state.search="";render()}));
  document.querySelector("[data-menu]")?.addEventListener("click",()=>document.querySelector("#mobileNav")?.classList.toggle("open"));
  document.querySelector("[data-logout]")?.addEventListener("click",()=>{logout();render()});
  bindThemeMenu();
  document.querySelector("#globalSearch")?.addEventListener("input",e=>{state.search=e.target.value;refreshPageData()});
  document.querySelector("[data-add-book]")?.addEventListener("click",()=>bookForm());
  document.querySelector("[data-add-member]")?.addEventListener("click",()=>memberForm());
  document.querySelectorAll("[data-open-issue]").forEach(x=>x.addEventListener("click",()=>issueForm()));
  document.querySelector("[data-backup]")?.addEventListener("click",()=>{download("library-management-backup.json",JSON.stringify(exportDB(state.db),null,2),"application/json");toast("Backup downloaded.")});
  document.querySelector("#restoreInput")?.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{const db=importDB(JSON.parse(await file.text()));if(confirm("Restore this backup? Current database will be replaced.")){state.db=db;persist();logout();render();toast("Backup restored. Sign in again.")}}catch{toast("Invalid Library Management backup.","error")}finally{e.target.value=""}});
  document.querySelector("[data-clear]")?.addEventListener("click",()=>{if(confirm("Clear the entire database? Download a backup first.")){clearDB();location.reload()}});
  document.querySelector("[data-reset-settings]")?.addEventListener("click",()=>renderSettingsFields(DEFAULT_SETTINGS));
  document.querySelector("#settingsForm")?.addEventListener("submit",saveSettings);
  document.querySelector("[data-export]")?.addEventListener("click",()=>{});
  document.querySelectorAll("[data-export]").forEach(x=>x.addEventListener("click",()=>exportCSV(x.dataset.export)));
  document.querySelector("#bookSearch")?.addEventListener("input",e=>{state.bookSearch=e.target.value;renderBooks()});
  document.querySelector("#memberSearch")?.addEventListener("input",e=>{state.memberSearch=e.target.value;renderMembers()});
  bindDynamicActions();
}
function bindDynamicActions(){
  document.querySelectorAll("[data-edit-book]").forEach(x=>x.addEventListener("click",()=>bookForm(x.dataset.editBook)));
  document.querySelectorAll("[data-delete-book]").forEach(x=>x.addEventListener("click",()=>deleteBook(x.dataset.deleteBook)));
  document.querySelectorAll("[data-edit-member]").forEach(x=>x.addEventListener("click",()=>memberForm(x.dataset.editMember)));
  document.querySelectorAll("[data-toggle-member]").forEach(x=>x.addEventListener("click",()=>toggleMember(x.dataset.toggleMember)));
  document.querySelectorAll("[data-view-member]").forEach(x=>x.addEventListener("click",()=>viewMember(x.dataset.viewMember)));
  document.querySelectorAll("[data-return]").forEach(x=>x.addEventListener("click",()=>returnBook(x.dataset.return)));
  document.querySelectorAll("[data-renew]").forEach(x=>x.addEventListener("click",()=>renew(x.dataset.renew)));
  document.querySelectorAll("[data-pay]").forEach(x=>x.addEventListener("click",()=>payFine(x.dataset.pay)));
  document.querySelectorAll("[data-cancel-res]").forEach(x=>x.addEventListener("click",()=>cancelReservation(x.dataset.cancelRes)));
  document.querySelectorAll("[data-reserve]").forEach(x=>x.addEventListener("click",()=>reservationForm(x.dataset.reserve)));
}
function refreshPageData(){if(state.page==="books")renderBooks();if(state.page==="members")renderMembers();if(state.page==="circulation")renderLoans();if(state.page==="reservations")renderReservations();if(state.page==="fines")renderFines();if(state.page==="notifications")renderNotifications();if(state.page==="audit")renderAudit();if(state.page==="settings")renderSettingsFields(state.db.settings)}
function renderBooks(){const body=document.querySelector("#bookRows"),count=document.querySelector("#bookCount");if(!body)return;const q=state.bookSearch.trim().toLowerCase(),list=state.db.books.filter(b=>`${b.title} ${b.author} ${b.isbn} ${b.genre}`.toLowerCase().includes(q));count.textContent=`${list.length} title${list.length===1?"":"s"}`;body.innerHTML=list.length?list.map(b=>`<tr><td><div class="book-title"><b>${esc(b.title)}</b><small>${esc(b.author)}</small></div></td><td>${esc(b.isbn)}</td><td>${esc(b.genre)}</td><td>${b.copies}</td><td><span class="badge ${available(b)>0?"good":"bad"}">${available(b)}</span></td><td>${b.year||"—"}</td><td><div class="row-actions"><button class="btn secondary xs" data-edit-book="${b.id}">Edit</button><button class="btn secondary xs" data-reserve="${b.id}" ${available(b)>0?"disabled":""}>Reserve</button><button class="btn danger xs" data-delete-book="${b.id}">Delete</button></div></td></tr>`).join(""):`<tr><td colspan="7">${Pages.empty("No books found.")}</td></tr>`;bindDynamicActions()}
function renderMembers(){const body=document.querySelector("#memberRows"),count=document.querySelector("#memberCount");if(!body)return;const q=state.memberSearch.trim().toLowerCase(),list=state.db.users.filter(u=>u.role==="member"&&`${u.name} ${u.rollNumber||""} ${u.username||""} ${u.email} ${u.phone||""}`.toLowerCase().includes(q));count.textContent=`${list.length} member${list.length===1?"":"s"}`;body.innerHTML=list.length?list.map(u=>`<tr><td><div class="member-cell"><span class="avatar">${esc(initials(u.name))}</span><div class="member-name"><b>${esc(u.name)}</b><small>${esc(u.username?"Login enabled":"No login")}</small></div></div></td><td><span class="roll-chip">${esc(u.rollNumber||"—")}</span></td><td>${esc(u.email)}<br><small class="muted">${esc(u.phone||"No phone")}</small></td><td>${esc(u.memberType||"Member")}</td><td>${activeLoans(u.id).length}</td><td>${money(unpaid(u.id).reduce((a,x)=>a+Number(x.amount||0),0),state.db.settings.currency)}</td><td><span class="badge ${u.active===false?"bad":"good"}">${u.active===false?"Disabled":"Active"}</span></td><td><div class="row-actions"><button class="btn secondary xs" data-view-member="${u.id}">View</button><button class="btn secondary xs" data-edit-member="${u.id}">Edit</button><button class="btn warning xs" data-toggle-member="${u.id}">${u.active===false?"Enable":"Disable"}</button></div></td></tr>`).join(""):`<tr><td colspan="8">${Pages.empty("No members found.")}</td></tr>`;bindDynamicActions()}
function renderLoans(){const body=document.querySelector("#loanRows");if(!body)return;const list=state.db.loans.filter(x=>!x.returned);body.innerHTML=list.length?list.map(l=>{const b=state.db.books.find(x=>x.id===l.bookId),m=state.db.users.find(x=>x.id===l.memberId),over=l.dueDate<today();return `<tr><td>${esc(b?.title||"Book")}</td><td>${esc(m?.name||"Member")}</td><td>${formatDate(l.issueDate,state.db.settings.dateFormat)}</td><td>${formatDate(l.dueDate,state.db.settings.dateFormat)}</td><td><span class="badge ${over?"bad":"good"}">${over?"Overdue":"On loan"}</span></td><td><div class="row-actions"><button class="btn secondary xs" data-renew="${l.id}">Renew</button><button class="btn success xs" data-return="${l.id}">Return</button></div></td></tr>`}).join(""):`<tr><td colspan="6">${Pages.empty("No active loans.")}</td></tr>`;bindDynamicActions()}
function renderReservations(){const body=document.querySelector("#reservationRows");if(!body)return;body.innerHTML=state.db.reservations.length?state.db.reservations.map(r=>`<tr><td>${esc(state.db.books.find(b=>b.id===r.bookId)?.title||"Book")}</td><td>${esc(state.db.users.find(u=>u.id===r.memberId)?.name||"Member")}</td><td>${formatDate(r.createdAt,state.db.settings.dateFormat)}</td><td><span class="badge">${esc(r.status)}</span></td><td>${r.status==="active"?`<button class="btn secondary xs" data-cancel-res="${r.id}">Cancel</button>`:""}</td></tr>`).join(""):`<tr><td colspan="5">${Pages.empty("No reservations.")}</td></tr>`;bindDynamicActions()}
function renderFines(){const body=document.querySelector("#fineRows");if(!body)return;body.innerHTML=state.db.fines.length?state.db.fines.map(f=>`<tr><td>${esc(state.db.users.find(u=>u.id===f.memberId)?.name||"Member")}</td><td>${esc(state.db.books.find(b=>b.id===f.bookId)?.title||"Book")}</td><td><b>${money(f.amount,state.db.settings.currency)}</b></td><td>${formatDate(f.createdAt,state.db.settings.dateFormat)}</td><td><span class="badge ${f.paid?"good":"bad"}">${f.paid?"Paid":"Unpaid"}</span></td><td>${f.paid?"":`<button class="btn success xs" data-pay="${f.id}">Mark paid</button>`}</td></tr>`).join(""):`<tr><td colspan="6">${Pages.empty("No fines.")}</td></tr>`;bindDynamicActions()}
function renderNotifications(){const el=document.querySelector("#notificationList");if(!el)return;el.innerHTML=state.db.notifications.length?state.db.notifications.map(n=>`<div class="notification"><span class="dot"></span><div><b>${esc(n.title)}</b><p class="muted">${esc(n.text)}</p><small class="muted">${formatDate(n.time,state.db.settings.dateFormat)}</small></div></div>`).join(""):Pages.empty("No notifications.");persist()}
function renderAudit(){const body=document.querySelector("#auditRows");if(!body)return;body.innerHTML=state.db.audit.length?state.db.audit.slice(0,250).map(a=>`<tr><td>${formatDate(a.time,state.db.settings.dateFormat)}</td><td>${esc(a.user)}</td><td>${esc(a.action)}</td><td>${esc(a.detail)}</td></tr>`).join(""):`<tr><td colspan="4">${Pages.empty("No activity yet.")}</td></tr>`}
function renderSettingsFields(s){const box=document.querySelector("#settingsFields");if(!box)return;box.innerHTML=`${field("libraryName","Library name",s.libraryName)}${field("emailDomains","Allowed email domains",(s.emailDomains||[]).join(", "))}<div class="form-grid two">${field("loanDays","Loan days",s.loanDays,"number","min=1 max=365 required")}${field("maxLoans","Maximum active loans",s.maxLoans,"number","min=1 max=50 required")}${field("maxRenewals","Maximum renewals",s.maxRenewals,"number","min=0 max=20 required")}${field("dailyFine","Fine per day",s.dailyFine,"number","min=0 step=0.5 required")}${field("reservationLimit","Reservation limit",s.reservationLimit,"number","min=0 max=50 required")}${field("reservationExpiryDays","Reservation expiry days",s.reservationExpiryDays,"number","min=1 max=30 required")}${field("fineGraceDays","Fine grace days",s.fineGraceDays,"number","min=0 max=30 required")}${select("itemsPerPage","Items per page",[[10,"10"],[25,"25"],[50,"50"]],s.itemsPerPage)}${select("currency","Currency",[["INR","₹ INR"],["USD","$ USD"],["EUR","€ EUR"],["GBP","£ GBP"]],s.currency)}${select("dateFormat","Date format",[["DD/MM/YYYY","DD/MM/YYYY"],["MM/DD/YYYY","MM/DD/YYYY"]],s.dateFormat)}</div>`;const tg=document.querySelector("#themeGrid");if(tg){tg.innerHTML=themes();tg.querySelectorAll("[data-theme]").forEach(x=>x.addEventListener("click",()=>setTheme(x.dataset.theme)))}const ss=document.querySelector("#storageStatus");if(ss)ss.innerHTML=`<div class="storage-status ${storageAvailable()?"storage-good":"storage-bad"}>${storageAvailable()?"✓ LocalStorage is available for this origin.":"! LocalStorage is unavailable in this browser/origin."}</div>`}
function saveSettings(e){e.preventDefault();const fd=new FormData(e.currentTarget),err=document.querySelector("#settingsError");err.textContent="";const domains=String(fd.get("emailDomains")||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(domains.some(x=>!/^[a-z0-9-]+(?:\.[a-z0-9-]+)+$/.test(x)))return err.textContent="Enter valid domains separated by commas.";const nums=["loanDays","maxLoans","maxRenewals","dailyFine","reservationLimit","reservationExpiryDays","fineGraceDays","itemsPerPage"];const next={...state.db.settings,libraryName:String(fd.get("libraryName")).trim()||"Library Management",emailDomains:[...new Set(domains)],currency:String(fd.get("currency")),dateFormat:String(fd.get("dateFormat"))};for(const n of nums){const v=Number(fd.get(n));if(!Number.isFinite(v)||v<0)return err.textContent=`Invalid value: ${n}`;next[n]=v}if(next.loanDays<1||next.maxLoans<1||next.itemsPerPage<1)return err.textContent="Loan days, maximum loans and items per page must be positive.";state.db.settings=next;persist();audit("Update settings");persist();toast("Settings saved.");render()}
function deleteBook(id){const b=state.db.books.find(x=>x.id===id);if(!b)return;if(state.db.loans.some(x=>x.bookId===id&&!x.returned)||state.db.reservations.some(x=>x.bookId===id&&x.status==="active"))return toast("Return active loans and cancel reservations first.","error");if(!confirm(`Delete “${b.title}”?`))return;state.db.books=state.db.books.filter(x=>x.id!==id);audit("Delete book",b.title);persist();toast("Book deleted.");render()}
function toggleMember(id){const u=state.db.users.find(x=>x.id===id);if(!u)return;u.active=u.active===false;audit(u.active?"Enable member":"Disable member",u.username);persist();toast(u.active?"Member enabled.":"Member disabled.");render()}
function viewMember(id){const u=state.db.users.find(x=>x.id===id);if(!u)return;const loans=activeLoans(id),fine=unpaid(id).reduce((a,x)=>a+Number(x.amount||0),0);import("./ui.js").then(({openModal})=>openModal("Member profile",`<div class="profile"><span class="avatar-lg">${esc(initials(u.name))}</span><div><h2>${esc(u.name)}</h2><p class="muted">${esc(u.memberType||"Member")}</p></div></div><div class="statline"><span>Roll number</span><b>${esc(u.rollNumber||"—")}</b></div><div class="statline"><span>Login username</span><b>${esc(u.username||"Not enabled")}</b></div><div class="statline"><span>Email</span><b>${esc(u.email)}</b></div><div class="statline"><span>Phone</span><b>${esc(u.phone||"—")}</b></div><div class="statline"><span>Current loans</span><b>${loans.length}</b></div><div class="statline"><span>Outstanding fines</span><b>${money(fine,state.db.settings.currency)}</b></div>`))}
function returnBook(id){const l=state.db.loans.find(x=>x.id===id);if(!l||l.returned)return;l.returned=true;const overdue=Math.max(0,Math.ceil((Date.now()-new Date(`${l.dueDate}T23:59:59`))/86400000)-state.db.settings.fineGraceDays),fine=overdue*state.db.settings.dailyFine;if(fine)state.db.fines.push({id:crypto.randomUUID?.()||Date.now()+"",memberId:l.memberId,bookId:l.bookId,loanId:l.id,amount:fine,paid:false,createdAt:Date.now()});notify(l.memberId,"Book returned",fine?`A fine of ${money(fine,state.db.settings.currency)} was added.`:"Book returned successfully.");audit("Return book",state.db.books.find(b=>b.id===l.bookId)?.title||"Book");persist();toast("Book returned.");render()}
function renew(id){const l=state.db.loans.find(x=>x.id===id);if(!l||l.returned)return;if(l.renewals>=state.db.settings.maxRenewals)return toast("Maximum renewals reached.","error");if(l.dueDate<today())return toast("Overdue books cannot be renewed.","error");l.renewals++;l.dueDate=addDays(l.dueDate,state.db.settings.loanDays);audit("Renew book",state.db.books.find(b=>b.id===l.bookId)?.title||"Book");persist();toast("Loan renewed.");render()}
function payFine(id){const f=state.db.fines.find(x=>x.id===id);if(!f)return;f.paid=true;f.paidAt=Date.now();audit("Mark fine paid",money(f.amount,state.db.settings.currency));persist();toast("Fine marked paid.");render()}
function cancelReservation(id){const r=state.db.reservations.find(x=>x.id===id);if(!r)return;r.status="cancelled";r.updatedAt=Date.now();audit("Cancel reservation");persist();toast("Reservation cancelled.");render()}
function exportCSV(type){let rows=[];if(type==="books")rows=[["Title","Author","ISBN","Genre","Publisher","Year","Copies","Available","Price","Rating"],...state.db.books.map(b=>[b.title,b.author,b.isbn,b.genre,b.publisher,b.year,b.copies,available(b),b.price,b.rating])];if(type==="members")rows=[["Name","Roll number","Login username","Email","Phone","Type","Status"],...state.db.users.filter(x=>x.role==="member").map(x=>[x.name,x.rollNumber||"",x.username||"",x.email,x.phone,x.memberType,x.active===false?"Disabled":"Active"])];if(type==="loans")rows=[["Book","Member","Roll number","Issued","Due","Returned"],...state.db.loans.map(x=>[state.db.books.find(b=>b.id===x.bookId)?.title,state.db.users.find(u=>u.id===x.memberId)?.name,state.db.users.find(u=>u.id===x.memberId)?.rollNumber||"",x.issueDate,x.dueDate,x.returned?"Yes":"No"])];if(type==="fines")rows=[["Member","Book","Amount","Paid","Date"],...state.db.fines.map(x=>[state.db.users.find(u=>u.id===x.memberId)?.name,state.db.books.find(b=>b.id===x.bookId)?.title,x.amount,x.paid?"Yes":"No",formatDate(x.createdAt,state.db.settings.dateFormat)])];download(`library-${type}.csv`,csv(rows),"text/csv");toast("CSV downloaded.")}

globalThis.addEventListener?.("lm-refresh",render);
